const EC_KEY='etatCivilSubmissions';
const PROVINCES=['Bas-Uele','Équateur','Haut-Katanga','Haut-Lomami','Haut-Uele','Ituri','Kasaï','Kasaï-Central','Kasaï-Oriental','Kinshasa','Kongo Central','Kwango','Kwilu','Lomami','Lualaba','Mai-Ndombe','Maniema','Mongala','Nord-Kivu','Nord-Ubangi','Sankuru','Sud-Kivu','Sud-Ubangi','Tanganyika','Tshopo','Tshuapa'];
const KIN_COMMUNES=['Bandalungwa','Barumbu','Bumbu','Gombe','Kalamu','Kasa-Vubu','Kimbanseke','Kinshasa','Kintambo','Kisenso','Lemba','Limete','Lingwala','Makala','Maluku','Masina','Matete','Mont-Ngafula','Ndjili','Ngaba','Ngaliema','Ngiri-Ngiri','Nsele','Selembao'];
function toast(msg){const t=document.querySelector('.toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function records(){try{return JSON.parse(localStorage.getItem(EC_KEY)||'[]')}catch{return []}}
function saveRecords(v){localStorage.setItem(EC_KEY,JSON.stringify(v))}
function makeId(type='N'){return `RDC-${new Date().getFullYear()}-${type}-${String(Date.now()).slice(-8)}`}
function aiExamine(data){const missing=['province','commune','citizenLastName','citizenFirstName','birthDate'].filter(k=>!String(data[k]||'').trim());return {score:missing.length?62:96,status:missing.length?'À compléter':'Pré-contrôlé par IA',missing,route:`${data.commune||'Centre à confirmer'} · ${data.province||'Province à confirmer'}`}}
function routeCitizenSubmission(form){const data=Object.fromEntries(new FormData(form));const ai=aiExamine(data);const rec={id:makeId('N'),type:'Naissance',createdAt:new Date().toISOString(),...data,aiScore:ai.score,status:ai.status,aiMissing:ai.missing,assignedTo:ai.route};const all=records();all.unshift(rec);saveRecords(all);localStorage.setItem('etatCivilCitizenLast',JSON.stringify(rec));return rec}
function provinceCounts(){const out=Object.fromEntries(PROVINCES.map(p=>[p,0]));records().filter(r=>r.type==='Naissance').forEach(r=>{if(out[r.province]!==undefined)out[r.province]++});return out}
function renderProvinceSummary(){const box=document.querySelector('[data-province-summary]');if(!box)return;const counts=provinceCounts();const total=Object.values(counts).reduce((a,b)=>a+b,0);box.textContent=`${total} naissance${total===1?'':'s'} enregistrée${total===1?'':'s'} dans la plateforme`}
function renderCitizenStatus(){const box=document.querySelector('[data-citizen-status]');if(!box)return;let r;try{r=JSON.parse(localStorage.getItem('etatCivilCitizenLast')||'null')}catch{}if(!r){box.innerHTML='<p>Aucune demande envoyée.</p>';return}box.innerHTML=`<div class="badge badge-blue">${r.status}</div><h3>${r.id}</h3><p><b>Transmission :</b> ${r.assignedTo}</p><p><b>Score de contrôle IA :</b> ${r.aiScore}%</p><p><b>Date :</b> ${new Date(r.createdAt).toLocaleString('fr-FR')}</p>`}
function renderAgentCitizenQueue(){const tbody=document.querySelector('[data-citizen-queue]');if(!tbody)return;const current=(document.body.dataset.commune||'Gombe').toLowerCase();const rows=records().filter(r=>(r.commune||'').toLowerCase()===current||current==='all').slice(0,12);tbody.innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${i+1}</td><td>${r.type}</td><td>${r.citizenLastName||''} ${r.citizenFirstName||''}</td><td>${r.commune}</td><td><span class="badge badge-blue">${r.status}</span></td><td><a href="province.html?province=${encodeURIComponent(r.province)}">Voir</a></td></tr>`).join(''):'<tr><td colspan="6">Aucune nouvelle demande citoyenne dans cette commune.</td></tr>'}
function renderNational(){const body=document.querySelector('[data-national-records]');if(body){const rows=records().slice(0,12);body.innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.createdAt).toLocaleDateString('fr-FR')}</td><td>${r.province}</td><td>${r.commune}</td><td>${r.type}</td><td>${r.status}</td></tr>`).join(''):'<tr><td colspan="5">Aucune nouvelle demande citoyenne.</td></tr>'}const total=document.querySelector('[data-total-submissions]');if(total)total.textContent=records().length}
function renderProvincePage(){const title=document.querySelector('[data-province-title]');if(!title)return;const p=new URLSearchParams(location.search).get('province')||'Kinshasa';title.textContent=p;const rows=records().filter(r=>r.province===p);const birth=rows.filter(r=>r.type==='Naissance').length;document.querySelector('[data-province-births]').textContent=birth;document.querySelector('[data-province-total]').textContent=rows.length;const tbody=document.querySelector('[data-province-records]');tbody.innerHTML=rows.length?rows.map(r=>`<tr><td>${r.id}</td><td>${r.commune}</td><td>${r.type}</td><td>${r.status}</td><td>${new Date(r.createdAt).toLocaleString('fr-FR')}</td></tr>`).join(''):'<tr><td colspan="5">Aucune demande enregistrée pour cette province.</td></tr>'}
function setupProvinceSelect(){const province=document.querySelector('#citizen-province');const commune=document.querySelector('#citizen-commune');if(!province||!commune)return;province.innerHTML='<option value="">Choisir une province</option>'+PROVINCES.map(p=>`<option>${p}</option>`).join('');function fill(){if(province.value==='Kinshasa'){commune.innerHTML='<option value="">Choisir une commune</option>'+KIN_COMMUNES.map(c=>`<option>${c}</option>`).join('')}else{commune.innerHTML='<option value="">Choisir / saisir votre commune</option>';commune.insertAdjacentHTML('afterend','') }}province.addEventListener('change',fill);fill()}
function init(){
 document.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();toast(el.dataset.toast)}));
 document.querySelectorAll('[data-save-form]').forEach(btn=>btn.addEventListener('click',()=>{const form=btn.closest('form')||document.querySelector('form');if(!form)return;localStorage.setItem('etat-civil-current-draft',JSON.stringify(Object.fromEntries(new FormData(form))));toast('Brouillon enregistré avec succès.')}));
 document.querySelectorAll('[data-submit-demo]').forEach(btn=>btn.addEventListener('click',()=>{const form=btn.closest('form')||document.querySelector('form');if(form&&!form.reportValidity())return;toast('Dossier soumis pour contrôle.')}));
 document.querySelectorAll('[data-search-act]').forEach(btn=>btn.addEventListener('click',()=>{const v=document.querySelector('#act-number')?.value.trim()||'';const result=document.querySelector('#verification-result');if(!v){toast('Entrez un numéro d’acte.');return;}if(result){result.hidden=false;result.querySelector('[data-act-value]')?.replaceChildren(document.createTextNode(v));}toast('Vérification effectuée.')}));
 document.querySelectorAll('[data-camera]').forEach(btn=>btn.addEventListener('click',async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});toast('Caméra activée.');setTimeout(()=>s.getTracks().forEach(t=>t.stop()),12000)}catch{toast('Autorisez l’accès à la caméra pour scanner le QR code.')}}));
 const login=document.querySelector('#login-form');if(login)login.addEventListener('submit',e=>{e.preventDefault();const role=document.querySelector('#login-role')?.value||'citizen';sessionStorage.setItem('etatCivilRole',role);location.href=role==='admin'?'admin.html':role==='agent'?'agent.html':'citoyen.html'});
 const citizen=document.querySelector('#citizen-registration');if(citizen)citizen.addEventListener('submit',e=>{e.preventDefault();if(!citizen.reportValidity())return;const r=routeCitizenSubmission(citizen);toast(`Demande transmise à ${r.assignedTo}`);setTimeout(()=>location.href='citoyen.html?sent=1',700)});
 setupProvinceSelect();renderCitizenStatus();renderAgentCitizenQueue();renderNational();renderProvincePage();renderProvinceSummary();
}
document.addEventListener('DOMContentLoaded',init);