function toast(msg){const t=document.querySelector('.toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function init(){
 document.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();toast(el.dataset.toast)}));
 document.querySelectorAll('[data-save-form]').forEach(btn=>btn.addEventListener('click',()=>{const form=btn.closest('form')||document.querySelector('form');if(!form)return;const data={};new FormData(form).forEach((v,k)=>data[k]=v);localStorage.setItem('etat-civil-current-draft',JSON.stringify(data));toast('Brouillon enregistré avec succès.')}));
 document.querySelectorAll('[data-submit-demo]').forEach(btn=>btn.addEventListener('click',()=>{const form=btn.closest('form')||document.querySelector('form');if(form&&!form.reportValidity())return;toast('Dossier soumis pour contrôle.')}));
 document.querySelectorAll('[data-search-act]').forEach(btn=>btn.addEventListener('click',()=>{const v=document.querySelector('#act-number')?.value.trim()||'';const result=document.querySelector('#verification-result');if(!v){toast('Entrez un numéro d’acte.');return;}if(result){result.hidden=false;result.querySelector('[data-act-value]')?.replaceChildren(document.createTextNode(v));}toast('Vérification effectuée.')}));
 document.querySelectorAll('[data-camera]').forEach(btn=>btn.addEventListener('click',async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});toast('Caméra activée.');setTimeout(()=>s.getTracks().forEach(t=>t.stop()),12000)}catch{toast('Autorisez l’accès à la caméra pour scanner le QR code.')}}));
 const stored=localStorage.getItem('etat-civil-current-draft');if(stored&&document.querySelector('form')){try{const d=JSON.parse(stored);Object.entries(d).forEach(([k,v])=>{const f=document.querySelector(`[name="${k}"]`);if(f&&!f.value)f.value=v})}catch{}}
 const login=document.querySelector('#login-form');if(login)login.addEventListener('submit',e=>{e.preventDefault();const role=document.querySelector('#login-role')?.value||'agent';sessionStorage.setItem('etatCivilRole',role);location.href=role==='admin'?'admin.html':'agent.html'});
 const signup=document.querySelector('#signup-form');if(signup)signup.addEventListener('submit',e=>{e.preventDefault();if(!signup.reportValidity())return;localStorage.setItem('etatCivilAccountCreated','1');toast('Compte créé. Vous pouvez maintenant vous connecter.');setTimeout(()=>location.href='connexion.html',900)});
}
document.addEventListener('DOMContentLoaded',init);
