const EC_DOC_KEY='etatCivilDocumentRequests';
function docRequests(){try{return JSON.parse(localStorage.getItem(EC_DOC_KEY)||'[]')}catch{return []}}
function saveDocRequests(v){localStorage.setItem(EC_DOC_KEY,JSON.stringify(v))}
function docId(){return `DOC-${new Date().getFullYear()}-${String(Date.now()).slice(-9)}`}
function verificationToken(){const bytes=new Uint8Array(12);crypto.getRandomValues(bytes);return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
function requestDocument(form){const data=Object.fromEntries(new FormData(form));const r={requestId:docId(),createdAt:new Date().toISOString(),status:'Demande reçue',history:[{at:new Date().toISOString(),action:'Demande reçue',actor:'Citoyen'}],...data};const all=docRequests();all.unshift(r);saveDocRequests(all);localStorage.setItem('etatCivilLastDocumentRequest',r.requestId);return r}
function issueDocument(requestId){const all=docRequests();const r=all.find(x=>x.requestId===requestId);if(!r)return null;if(r.status==='Document émis')return r;r.status='Document émis';r.issuedAt=new Date().toISOString();r.documentNumber=`RDC-${new Date().getFullYear()}-${String(Date.now()).slice(-10)}`;r.verificationToken=verificationToken();r.history.push({at:r.issuedAt,action:'Document émis',actor:'Agent d’état civil'});saveDocRequests(all);return r}
function findDocument(query){return docRequests().find(r=>r.documentNumber===query||r.verificationToken===query||r.requestId===query)}
function renderCitizenDocumentArea(){const main=document.querySelector('.citizen-wrap');if(!main||document.querySelector('#citizen-documents'))return;const all=docRequests();const s=document.createElement('section');s.id='citizen-documents';s.className='citizen-card';s.style.marginTop='20px';s.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h2 style="margin-bottom:4px">Mes demandes de documents</h2><p class="section-sub">Suivez la demande jusqu’à la délivrance et récupérez le document numérique.</p></div><a class="btn btn-primary" href="demande-document.html">Demander un document</a></div><div class="table-scroll"><table><thead><tr><th>Demande</th><th>Document</th><th>Province</th><th>Commune</th><th>Statut</th><th>Action</th></tr></thead><tbody>${all.length?all.map(r=>`<tr><td>${r.requestId}<br><small>${new Date(r.createdAt).toLocaleString('fr-FR')}</small></td><td>${r.documentType}</td><td>${r.province}</td><td>${r.commune}</td><td><span class="badge ${r.status==='Document émis'?'badge-ok':'badge-blue'}">${r.status}</span></td><td>${r.status==='Document émis'?`<a href="document.html?id=${encodeURIComponent(r.requestId)}">Ouvrir</a>`:'En traitement'}</td></tr>`).join(''):'<tr><td colspan="6">Aucune demande de document.</td></tr>'}</tbody></table></div>`;main.appendChild(s)}
function renderAgentDocumentQueue(){const main=document.querySelector('.agent-main');if(!main||document.querySelector('#document-requests'))return;const all=docRequests();const s=document.createElement('section');s.id='document-requests';s.className='queue';s.style.marginTop='14px';s.innerHTML=`<h3>Demandes de documents en ligne <span class="badge badge-blue">${all.length}</span></h3><div class="table-scroll"><table><thead><tr><th>Demande</th><th>Citoyen</th><th>Document</th><th>Juridiction</th><th>Statut</th><th>Action</th></tr></thead><tbody>${all.length?all.map(r=>`<tr><td>${r.requestId}</td><td>${r.lastName} ${r.firstName}</td><td>${r.documentType}</td><td>${r.commune} · ${r.province}</td><td>${r.status}</td><td>${r.status==='Document émis'?`<a href="document.html?id=${encodeURIComponent(r.requestId)}">Voir</a>`:`<button class="btn btn-primary" data-issue-doc="${r.requestId}">Émettre</button>`}</td></tr>`).join(''):'<tr><td colspan="6">Aucune demande reçue.</td></tr>'}</tbody></table></div>`;main.appendChild(s);s.querySelectorAll('[data-issue-doc]').forEach(b=>b.addEventListener('click',()=>{const r=issueDocument(b.dataset.issueDoc);if(r){toast('Document émis avec QR de vérification.');renderAgentDocumentQueueRefresh()}}))}
function renderAgentDocumentQueueRefresh(){const old=document.querySelector('#document-requests');if(old)old.remove();renderAgentDocumentQueue()}
function initDocumentRequest(){const form=document.querySelector('#document-request-form');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const r=requestDocument(form);toast(`Demande ${r.requestId} envoyée à ${r.commune} · ${r.province}`);setTimeout(()=>location.href='citoyen.html',700)})}
function renderDigitalDocument(){const root=document.querySelector('[data-digital-document]');if(!root)return;const id=new URLSearchParams(location.search).get('id');const r=docRequests().find(x=>x.requestId===id);const status=root.querySelector('[data-document-status]');const fields=root.querySelector('[data-document-fields]');if(!r){status.innerHTML='<span class="revoked">Document introuvable</span>';fields.innerHTML='<p>Cette référence n’existe pas.</p>';return}if(r.status!=='Document émis'){status.innerHTML='<span class="pending">Document en attente de validation</span>';fields.innerHTML=`<div class="doc-field"><small>Demande</small><b>${r.requestId}</b></div><div class="doc-field"><small>Statut</small><b>${r.status}</b></div>`;return}status.innerHTML='<span class="valid">✓ Document valide</span>';fields.innerHTML=`<div class="doc-field"><small>Numéro du document</small><b>${r.documentNumber}</b></div><div class="doc-field"><small>Type</small><b>${r.documentType}</b></div><div class="doc-field"><small>Titulaire</small><b>${r.lastName} ${r.firstName}</b></div><div class="doc-field"><small>Juridiction</small><b>${r.commune}, ${r.province}</b></div><div class="doc-field"><small>Date d’émission</small><b>${new Date(r.issuedAt).toLocaleString('fr-FR')}</b></div><div class="doc-field"><small>Mode de livraison</small><b>${r.delivery}</b></div>`;root.querySelector('[data-document-code]').textContent=r.documentNumber;const verifyUrl=`${location.origin}/verification.html?token=${encodeURIComponent(r.verificationToken)}`;if(window.QRCode)new QRCode(document.getElementById('qr'),{text:verifyUrl,width:128,height:128})}
function initVerificationToken(){const token=new URLSearchParams(location.search).get('token');const input=document.querySelector('#act-number');if(token&&input){input.value=token;verifyDocumentQuery(token)}const btn=document.querySelector('[data-search-act]');if(btn)btn.addEventListener('click',()=>verifyDocumentQuery(input?.value.trim()||''),true)}
function verifyDocumentQuery(q){if(!q)return;const r=findDocument(q);let box=document.querySelector('#digital-verification-result');if(!box){box=document.createElement('div');box.id='digital-verification-result';box.style.marginTop='18px';document.querySelector('#verification-result')?.parentElement?.appendChild(box)}if(!r||r.status!=='Document émis'){box.innerHTML='<div style="padding:16px;border:1px solid #f1c7c7;background:#fff5f5;color:#b12d2d"><b>Document non vérifié</b><p>Aucun document valide ne correspond à cette référence.</p></div>';return}box.innerHTML=`<div style="padding:16px;border:1px solid #bfe3cf;background:#f4fff8;color:#17643f"><b>✓ Document authentique et valide</b><p>Numéro : ${r.documentNumber}<br>Type : ${r.documentType}<br>Juridiction : ${r.commune}, ${r.province}<br>Émis le : ${new Date(r.issuedAt).toLocaleString('fr-FR')}</p></div>`;r.history.push({at:new Date().toISOString(),action:'Document vérifié',actor:'Vérification publique'});saveDocRequests(docRequests().map(x=>x.requestId===r.requestId?r:x))}
document.addEventListener('DOMContentLoaded',()=>{initDocumentRequest();renderCitizenDocumentArea();renderAgentDocumentQueue();renderDigitalDocument();initVerificationToken()});